# 配置文件重载命令: /aomreload
# 重载配置文件所需权限: "anotheronlinemode.admin"

# 验证正版账号的命令. 注:此项命令修改后必须重启插件生效!
command: "zb"

# 是否在玩家进入服务器后发送下面指定内容
alert: true

# %command% 为变量, 可使用'\n'换行, 支持'&'颜色字符
message: "&3&l你知道吗? 使用命令 %command% 可以验证正版账号, 但无需账号密码且支持微软正版!"

# 每个账号在每次运行中最多验证次数, 拥有权限 "anotheronlinemode.bypass" 的玩家无视此限制
times: 3

# 次数耗尽时提示, 支持'&'颜色字符
limit: "&c&l对不起, 您已用完验证次数, 请联系管理员验证~"

# 验证开始时, 提示玩家重新进入的提示语, 支持'&'颜色字符
start: "&e&l已准备完毕, 当你下次进入服务器时, 会验证你的账户是否为正版"

# 存放 List<String>, %player% 为变量, 按照格式写验证[成功]后在控制台所执行的命令(组)或发送的信息, 命令以'/'开头
success:
  - "/cmd1 [Test]"
  - "你的名字是: %player%"

# 存放 List<String>, %player% 为变量, 按照格式写验证[失败]后在控制台所执行的命令(组)或发送的信息, 命令以'/'开头
fail:
  - "/cmd2 [Test] (请更改此处)"
  - "你的名字是: %player%"

##### BungeeCord端插件只能执行BC的指令 如/lpb而不是/lp #####
